### Endpoint leads_index role manager
GET http://127.0.0.1:8000/api/leads
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJpc3MiOiJodHRwOi8vbG9jYWxob3N0IiwiYXVkIjoiaHR0cDovL2xvY2FsaG9zdCIsImlhdCI6MTY5ODcyNjk3NywibmJmIjoxNjk4NzI2OTc3LCJzdWIiOiJBUEktU0FHRyIsImRhdGEiOnsiVXNlcklEIjoxLCJVc2VyTmFtZSI6InRlc3RlciIsIlJvbGUiOiJtYW5hZ2VyIn19.cPXjTpO8urX74LOjT4SCpIjzeQHKfknY6I9NxDroyPY9Jcqem9n1cwcffsNJmnmqWa3n-1qXMQf0j3x381kpIg

### Endpoint leads_index role agent
GET http://127.0.0.1:8000/api/leads
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJpc3MiOiJodHRwOi8vbG9jYWxob3N0IiwiYXVkIjoiaHR0cDovL2xvY2FsaG9zdCIsImlhdCI6MTY5ODcyNjk5OSwibmJmIjoxNjk4NzI2OTk5LCJzdWIiOiJBUEktU0FHRyIsImRhdGEiOnsiVXNlcklEIjoyLCJVc2VyTmFtZSI6InBydWViYSIsIlJvbGUiOiJhZ2VudCJ9fQ.fD1GVEflDVuEhLILJl-D2X3evEDZtAhNSNYh1-z_icfJ4_jnYKQtS2Xs_APeFIDbDcY0UKUKoVMuDZlDkqxaGA