### Endpoint lead_create role manager
POST http://127.0.0.1:8000/api/lead
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJpc3MiOiJodHRwOi8vbG9jYWxob3N0IiwiYXVkIjoiaHR0cDovL2xvY2FsaG9zdCIsImlhdCI6MTY5ODYwOTExMiwibmJmIjoxNjk4NjA5MTEyLCJzdWIiOiJBUEktTU9OT01BIiwiZGF0YSI6eyJVc2VySUQiOjEsIlVzZXJOYW1lIjoidGVzdGVyIiwiUm9sZSI6Im1hbmFnZXIifX0.ivrObR5It5TkQ-Px_ozeAKU9w7FizuzB6yNELiAv9sRmPfI2cQarYFjaPN5gtk1_eKYYNrGdvxnYz7zPaQdWVQ

{
  "name": "Candidato infinite",
  "source": "ALL",
  "owner": 2
}

### Endpoint lead_create role agent
POST http://127.0.0.1:8000/api/lead
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJpc3MiOiJodHRwOi8vbG9jYWxob3N0IiwiYXVkIjoiaHR0cDovL2xvY2FsaG9zdCIsImlhdCI6MTY5ODYwOTE1NSwibmJmIjoxNjk4NjA5MTU1LCJzdWIiOiJBUEktTU9OT01BIiwiZGF0YSI6eyJVc2VySUQiOjIsIlVzZXJOYW1lIjoicHJ1ZWJhIiwiUm9sZSI6ImFnZW50In19.6UWORuMkWb5sCfRgxBXIZ3qvuaXx56fPhT6KKl6CEPjmxyLlAJLi9rwfrM0PG8XvCAHgnlEnHyUvVZJTDtVE_A

{
  "name": "Candidato infinite",
  "source": "ALL",
  "owner": 2
}